### PR TITLE
[webinterface.tex] 1.0.0

### PR DESCRIPTION
**Pull request by clementdelestre**
### Description
TeX is a new web interface for Kodi made with Angular and Tailwind CSS.
Source: https://github.com/clementdelestre/TeX

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-webinterfaces/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by romanvm** [comment]
Looks like you have included all Font Awesome distribution in the submission including development source files. I'd recommend to read the FA docs to learn what files are really needed to use FA in your web project: https://fontawesome.com/v5.15/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-web-fonts

**Comment by clementdelestre** [comment]
Thanks
I removed all the unnecessary files from font-awesome. 
However I didn't know how to edit the first commit from vscode so it created a second one :/

**Comment by razzeee** [comment]
If you want to do it via vscode, it should have been:

F1 > Amend 
F1 > Push (Force) 
the last one needs to be enabled in the settings

or you could do

F1 > Undo last commit
Go to the git view and add your changes, commit it again
F1 > Push (Force)

You likely would want to check `git log` before force pushing

**Comment by clementdelestre** [comment]
Ok I tried something but I really need to improve myself on how using github :'(
I will try to do better next time
Do you think the pull request can still be checked or I need to fix it before (to have just one commit)?

**Comment by razzeee** [comment]
Code and using it in kodi seems fine to me. But as the code is heavily minified, I will have to check out the source for that too and also build it and diff it with what you've send.

Can you please run https://pypi.org/project/kodi-addon-checker/ on your repo? Unfortunatly, we seem to have missed this repo, when we set that up.

**Comment by razzeee** [comment]
Btw, what kodi version would you want to target? Is jarvis okay or do you want a higher one?

**Comment by razzeee** [comment]
Could you try using fontawesome via npm? Would eliminate another block of minified (well it's only css anyway) code, that's checked in.

**Comment by razzeee** [comment]
Diff with main build on my machines shows some differences, but seems to be mostly css changes, so it should be fine to merge from that POV.

**Comment by razzeee** [comment]
Squashed an rebased, should hopefully run the checker now.

**Pull request merged**
