### PR TITLE
[webinterface.awxi] moved from gotham

### PR DESCRIPTION
**Pull request by bailus**

### CODE REVIEW

**Comment by Montellese** [comment]
@MartijnKaijser: is this necessary? Which repositories are available in Jarvis? Looks like `webinterface.awxi` never made it into Helix or Isengard.

**Comment by MartijnKaijser** [comment]
@Montellese remember the change we did on the extension name?
See here
https://github.com/bailus/awxi/commit/106b2626af7a8f5da93c74028c716662f76b940f

Adding both extension didn't work.

**Comment by Montellese** [comment]
Gave it a quick test with Jarvis and looks like it's still working.

**Comment by Montellese** [comment]
@mizaki: Are you ok with this being included in Jarvis?

**Comment by mizaki** [comment]
Fine with me but I've obviously not touched it in a long time. WRU Chorus 2? ;)

Date: Sun, 20 Mar 2016 02:25:20 -0700

**Comment by bailus** [comment]
> WRU Chorus

That was my conclusion after trying it, but it seems to work fine. If the overwhelming majority prefer Chorus it might be better to leave it out?

**Comment by Montellese** [comment]
So do you want to include AWXi in the Jarvis repository or not?

**Comment by mizaki** [comment]
Yes. Might as well.

Date: Mon, 21 Mar 2016 05:19:04 -0700

**Pull request merged**
