### PR TITLE
[webinterface.tex] 1.1.0

### PR DESCRIPTION
**Pull request by clementdelestre**
### Description
TeX is a new web interface for Kodi made with Angular and Tailwind CSS.
*Tested on Matrix (there is no Matrix branch for webinterface :/) *

-- Update v1.1.0 --
Changelogs :
- Fix many bugs for iOS devices
- Remote can now vibrate when clicking button
- Many improvements

Source: https://github.com/clementdelestre/TeX

### Checklist:

- [x ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-webinterfaces/blob/master/CONTRIBUTING.md) document
- [x ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

### CODE REVIEW

**Comment by clementdelestre** [comment]
I can't figure out how to fix the error "xbmc.webinterface dependency is required for xbmc.webinterface extensions" :(

**Comment by enen92** [comment]
Thanks much for the submission, glad to see some activity around webinterfaces. We should sort the absence of the matrix branch in this repo.
Regarding the addon check error, I think you found a bug :) https://github.com/xbmc/addon-check/blob/e0206983746f3ca96a3543b84fef512c68ea31d1/kodi_addon_checker/check_dependencies.py#L55 should be xbmc.json and not xbmc.webinterface. I'll fix it and draft a new release asap (maybe tonight)

**Comment by Klojum** [comment]
Just a small observation from the screenshots: "Musics" does not have a plural form in English, so it's just "Music".

Also, we can probably add your web-interface add-on to Weblate, Kodi's new translation service of choice, so several more languages can support your add-on. You can contact @gade01 for that, or @gade on the Kodi forum.

**Comment by gade01** [comment]
@Klojum @clementdelestre 
We can absolutely add the web-interface to Weblate for translation, once it's in the official repo.

**Comment by enen92** [comment]
The addon-checker issue should be fixed

**Comment by clementdelestre** [comment]
Great idea to use Weblate, it will make translation a lot easier
I try to do my best to translate in English but my level is quite bad...

Thanks for your support with the addon-checker issue, glad to see it's working now!

**Comment by clementdelestre** [comment]
This repo doesn't seem active anymore to merge pull requests..?

**Comment by razzeee** [comment]
It is, but I guess nobody had time to check this till now.

Also there has been a matrix branch created here, as you mentioned it. But It would likely make the review harder.

**Pull request merged**
